### PR TITLE
for pam 

### PR DESCRIPTION
**Pull request by NaveenSidhartha**
ssl_certs volumes for pam container

### CODE REVIEW

**Comment by maria-walsh** [comment]
@NaveenSidhartha  Should the nginx ssl cert volume also be the same as the nginx container in each pod? Currently the nginx volume is `/etc/nginx/certs:/etc/nginx/certs`. Should it also be `/etc/cloudcix/docker/ssl_certs:/etc/nginx/certs`?

**Comment by NaveenSidhartha** [comment]
> @NaveenSidhartha Should the nginx ssl cert volume also be the same as the nginx container in each pod? Currently the nginx volume is `/etc/nginx/certs:/etc/nginx/certs`. Should it also be `/etc/cloudcix/docker/ssl_certs:/etc/nginx/certs`?

@maria-walsh  This folder is for PAM gui application into where PAM operator uploads ssl_certs with pod[number] ie
/etc/cloudcix/docker/ssl_certs/{pod[number]}/ full chain.pem etc. these files will be available to PAM gui at /ssl_certs/{pod[number]}/full chain.pem 

Then a function in PAM gui looks for these at /ssl_certs/{pod[number]} and transfers them to remote location at /etc/nginx/certs/{cop_portal}/

Note: cop_portal need to be added to  pod table in PAM gui.

**Comment by maria-walsh** [comment]
Okay, I had thought we had discussed the certs being stored in the same volume as the nginx container which was why I asked. This makes sense though now.

cop_portal - I am confused by the pam needing to know this. When letsencrypt certs are generated the certs are added to the following path - /etc/letsencrypt/live/<domain_name>. It is this <domain_name> folder that is transferred to the volume that is mapped into the nginx container.

Once PAM transfers all folders in the path /etc/cloudcix/docker/ssl_certs/<pod_id>/ to /etc/nginx/certs/ on the pod, it should not need to know the domains it is transferring

**Comment by NaveenSidhartha** [comment]
Okay then, let the PAM Operator upload letsencrypt files generated from not PAM appliance with domain_name directly at /etc/cloudcix/docker/ssl_certs/<pod_id>/<domain_name>, it would be easy for pam gui.

So I understood that no need of domain_name by pam gui, just need to know should I use pod_id or pod_number?

**Comment by maria-walsh** [comment]
`pod_number` it will be easier for the PAM support team to know where to transfer files to onto the PAM appliance

**Comment by NaveenSidhartha** [comment]
Okay, I think you can  merge this.

**Pull request merged**
